In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from keras.utils import to_categorical
from sklearn.preprocessing import OneHotEncoder

# Loading Data

In [31]:
transacciones = pd.read_pickle('TestDF.pkl')
comunicaciones = pd.read_pickle('ComunicacionesTestGlobal.pkl')
consumidores = pd.read_pickle('Consumidores.pkl')

In [32]:
df1 = pd.merge(transacciones,comunicaciones, on = 'id' , how = 'left').fillna(0)

In [33]:
df1

,id,A-G,A-K,A-L,C-C,D-F,E-F,F-D,F-H,F-I,F-J,G-K,Lectura,ComAA,ComBB,ComCD
0,1,1149213,-4.900651e+06,0.0000,0.000000e+00,0,0,1.402857e+06,-1.402857e+06,-1402857.125,1.402857e+06,-2.690158e+06,1.0,0.0,1.0,0.0
1,2,1113246,-2.996131e+06,0.0000,-3.694527e+06,-121141,0,0.000000e+00,-3.600000e+05,0.000,3.600000e+05,-7.671284e+06,1.0,0.0,1.0,1.0
2,3,2510778,-4.986702e+06,0.0000,0.000000e+00,0,-123745,1.200361e+05,-3.600361e+05,0.000,3.600361e+05,-6.503626e+05,1.0,0.0,1.0,0.0
3,4,1122183,-1.001903e+06,548571.4375,0.000000e+00,0,-121428,0.000000e+00,-1.200000e+05,-240000.000,3.600000e+05,-2.947002e+06,1.0,0.0,0.0,1.0
4,5,494103,-6.065471e+05,0.0000,0.000000e+00,0,0,0.000000e+00,-3.600000e+05,-120000.000,3.600000e+05,-4.998845e+06,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79534,79535,678924,-1.171770e+06,0.0000,-6.029971e+05,-122047,0,0.000000e+00,-2.400000e+05,-360000.000,3.600000e+05,-7.566180e+06,1.0,0.0,1.0,0.0
79535,79536,713488,-3.674494e+05,0.0000,0.000000e+00,0,0,1.270000e+05,-1.200000e+05,-247000.000,2.470000e+05,-5.894302e+06,0.0,0.0,1.0,0.0
79536,79537,568955,-2.513046e+05,0.0000,0.000000e+00,0,-150370,1.028571e+06,-1.200000e+05,0.000,1.148571e+06,0.000000e+00,0.0,0.0,1.0,1.0
79537,79538,767589,-2.220285e+06,0.0000,0.000000e+00,0,0,0.000000e+00,-3.600000e+05,-360000.000,3.600000e+05,-2.487990e+05,1.0,0.0,1.0,0.0
79538,79539,0,0.000000e+00,0.0000,-2.163058e+06,0,-120714,0.000000e+00,-2.400000e+05,0.000,3.600000e+05,-2.346835e+06,1.0,0.0,1.0,1.0

In [34]:
df2 = pd.merge(df1 , consumidores , on ='id' , how = 'left')

In [37]:
df2.columns

Index(['id', 'A-G', 'A-K', 'A-L', 'C-C', 'D-F', 'E-F', 'F-D', 'F-H', 'F-I',
       'F-J', 'G-K', 'Lectura', 'ComAA', 'ComBB', 'ComCD', 'Sexo',
       'Recibe_sueldo_en_cuenta', 'Entre 25 y 30', 'Entre 30 y 35',
       'Entre 35 y 40', 'Entre 40 y 45', 'Entre 45 y 50', 'Entre 50 y 55',
       'Entre 55 y 60', 'Entre 60 y 65', 'Entre 65 y 70', 'Mayor a 70',
       'Menor a 25', 'R1', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16',
       'R17', 'R18', 'R19', 'R2', 'R20', 'R21', 'R3', 'R4', 'R5', 'R6', 'R7',
       'R8', 'R9', 'SegmentoConsumidor'],
      dtype='object')

In [28]:
df2.set_index('id' , inplace = True)

In [38]:
df2['ComDE'] = 0
df2['ComEE'] = 0

In [40]:
df2 = df2[['A-G', 'A-K', 'A-L', 'C-C', 'D-F', 'E-F', 'F-D', 'F-H', 'F-I', 'F-J',
       'G-K', 'Lectura', 'ComAA', 'ComBB', 'ComCD', 'ComDE', 'ComEE', 'Sexo',
       'Recibe_sueldo_en_cuenta', 'Entre 25 y 30', 'Entre 30 y 35',
       'Entre 35 y 40', 'Entre 40 y 45', 'Entre 45 y 50', 'Entre 50 y 55',
       'Entre 55 y 60', 'Entre 60 y 65', 'Entre 65 y 70', 'Mayor a 70',
       'Menor a 25', 'R1', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16',
       'R17', 'R18', 'R19', 'R2', 'R20', 'R21', 'R3', 'R4', 'R5', 'R6', 'R7',
       'R8', 'R9', 'SegmentoConsumidor']]

In [41]:
df2

,A-G,A-K,A-L,C-C,D-F,E-F,F-D,F-H,F-I,F-J,...,R20,R21,R3,R4,R5,R6,R7,R8,R9,SegmentoConsumidor
0,1149213,-4.900651e+06,0.0000,0.000000e+00,0,0,1.402857e+06,-1.402857e+06,-1402857.125,1.402857e+06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1113246,-2.996131e+06,0.0000,-3.694527e+06,-121141,0,0.000000e+00,-3.600000e+05,0.000,3.600000e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2510778,-4.986702e+06,0.0000,0.000000e+00,0,-123745,1.200361e+05,-3.600361e+05,0.000,3.600361e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1122183,-1.001903e+06,548571.4375,0.000000e+00,0,-121428,0.000000e+00,-1.200000e+05,-240000.000,3.600000e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,494103,-6.065471e+05,0.0000,0.000000e+00,0,0,0.000000e+00,-3.600000e+05,-120000.000,3.600000e+05,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79534,678924,-1.171770e+06,0.0000,-6.029971e+05,-122047,0,0.000000e+00,-2.400000e+05,-360000.000,3.600000e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79535,713488,-3.674494e+05,0.0000,0.000000e+00,0,0,1.270000e+05,-1.200000e+05,-247000.000,2.470000e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79536,568955,-2.513046e+05,0.0000,0.000000e+00,0,-150370,1.028571e+06,-1.200000e+05,0.000,1.148571e+06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79537,767589,-2.220285e+06,0.0000,0.000000e+00,0,0,0.000000e+00,-3.600000e+05,-360000.000,3.600000e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79538,0,0.000000e+00,0.0000,-2.163058e+06,0,-120714,0.000000e+00,-2.400000e+05,0.000,3.600000e+05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [10]:
#X.to_pickle('X.pkl')

In [11]:
#y.to_pickle('y.pkl')

In [42]:
df2.to_csv('XTest.csv')

In [17]:
y.to_csv('y4.csv')

In [18]:
X

,A-K,A-L,C-C,D-F,E-F,F-D,F-H,F-I,F-J,G-K,...,R20,R21,R3,R4,R5,R6,R7,R8,R9,SegmentoConsumidor
0,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,1,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,1,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79534,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79535,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79536,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79537,0,0,0,0,0,1,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
79538,0,0,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0